# Data preprocessing
input_file: "data/Участники anonimized.csv"
path_to_csv_files: "data/anonimized"
categorical_columns:
- "EX-Категория"
numeric_columns:
- "Возраст"
- "Баллы, %"
output_file: "clustered_data/clustered.csv"

# choice: ["DBSCAN", "AgglomerativeClustering", "kmeans"]
cluster_method: "kmeans"

# save elbow plot for kmeans method (if you want)
is_save_elbow_plot: False
save_elbow_plot_path: "elbow_plot.png"

# Cluster params

## DBSCAN
eps: 0.3
min_samples: 20

## for AgglomerativeClustering or KMeans
n_clusters: 4
